### ISSUE TITLE
Proposal: change list-item values from concepts to string

### ISSUE THREAD

**Issue by ulfulf** [amrisi/amr-guidelines#160]
**Current AMR Dict entry for :li**
http://www.isi.edu/~ulf/amr/lib/amr-dict.html#:li

**Current policy** 
  * :li (x / 1) :li (x2 / 2) :li (x3 / 3)
  * :li (a / a) :li (b / b) :li (c / c)
  * :li (i / i) :li (i2 / ii) :li (i3 / iii)  

**Proposed policy**
  * :li 1 :li 2 :li 3  ... :li "-1" (for "lastly", in analogy to ordinals)
  * :li "a" :li "b" :li "c"
  * :li "i" :li "ii" :li "iii"

**Current reality**
  * inconsistent annotation
  * 130+ instances conforming to current policy
  * 30+ instances conforming to proposed policy

**Motivation**
  * AMRs more legible.
  * Proposed policy more consistent with rest of AMR. 
     * Chapter 2: (c / chapter :mod 2)  
     * Figure 5b: (f / figure :mod "5b")
  * *2/b/ii* etc. are not really concepts. 
  * Interference with AMR checking.
      * Should concept *i* really be shared for the *i/I* in "(i) Opening Remarks" and "I made some remarks."?
  * list-items do not have complex structure (after all).
  * Automatic conversion possible.
  * AMR Editor could steer annotators to consistent new annotation.

**Comment by nschneid** [comment]
I like strings better than concepts. But I'm not sure I see the need to encode list item numbers at all—they are about the presentation of part of a sentence, not its meaning. Is the point to clarify that the order of items under `and` is not arbitrary? Wouldn't something like `(o / ordered-list :op1 (x1 ...) :op2 (x2 ...) :op3 (x3 ...))` be simpler?

**Comment by ulfulf** [comment]
Adopted by AMR meeting on Oct. 19, 2015 as proposed by Ulf.

Ulf updated AMR Dict at http://www.isi.edu/~ulf/amr/lib/amr-dict.html#list%20item as well as AMR Editor, AMR guidelines examples, AMR release corpus (automatically updated), AMR Checker; added have-li-91 as a reification for :li to be able to deal with a few cases of stranded list item markers.

@nschneid List item markers are typically spread over multiple sentences, so ```(o / ordered-list :op1 (x1 ...) :op2 (x2 ...) :op3 (x3 ...))``` would not work as simple as that in our current annotation setup.
