### ISSUE TITLE
'tough' ambiguity

### ISSUE THREAD

**Issue by nschneid** [amrisi/amr-guidelines#173]
Paraphrasing from an [article](http://www.huffingtonpost.com/mike-lux/charles-kochs-bernie-bs_b_9279030.html): "the law makes prosecution tougher". This is ambiguous, with opposite implications!

Reading 1: law makes it more difficult to prosecute (`tough-02`)

```lisp
(m / make-02
   :ARG0 (l / law)
   :ARG1 (t / tough-02
            :ARG1 (p / prosecute-01)
            :degree (m3 / more)))
```

Reading 2: law makes the prosecution more vigorous, tough on crime (`tough-03`)

```lisp
(m2 / make-02
    :ARG0 (l2 / law
    :ARG1 (t2 / tough-03
              :manner-of (p2 / prosecute-01)
              :degree (m4 / more)))
```

(Is `:manner-of` correct, or should a numbered argument be used for an event that doles out toughness?)

**Comment by kevincrawfordknight** [comment]
Looks good!
