### ISSUE TITLE
Inconsistency: "always" as :time but "often" as :frequency

### ISSUE THREAD

**Issue by nschneid** [amrisi/amr-guidelines#176]
Each decision seems fairly consistent in the corpus. But it seems like "always" describes a frequency.

**Comment by nschneid** [comment]
From searching the release data:

- always: `:time always`
- often: mix of `:frequency often` and `:time often`
- sometimes: mix of `:frequency sometimes` and `:time sometimes`
- never: `:polarity - :time ever`
- usually: mix of `:mod usual` and `:frequency usual`
- rarely: `:ARG1-of rare-02`
- frequently: `:ARG1-of frequent-02`
- occasionally: mix of `:frequency occasional` and `:time occasional`

**Comment by nschneid** [comment]
Relatedly:

- every time: mix of `rate-entity-91`, `:frequency time :mod every`, `:time every`
- each time: mix of `rate-entity-91`, `:frequency time :mod each`, `:time time :mod each`

**Comment by ulfulf** [comment]
I think that *always* and *sometimes*/*often* are somewhat different.

While *sometimes* and *often* are a strong match to the question *How often?*, *always* more strongly matches the question *When?*
    * Tanks are always dangerous.
    * How often are tanks dangerous? (more weird IMO)
    * When are tanks dangerous? (less weird IMO)

*:time* as single time interval:
    * in 2016 (closed time interval)
    * until 2016 (half open time interval)
    * always (open time interval)

Other examples where *always* does not match *How often?* very well:
    * We can always hope.
    * I have always been very introverted.
    * She has always lived in China.
    * He always helped me when I needed his help.

One could of course argue that *always* implies *once* but I think that *always* carries much more information than *once*.

In the past, annotation of *always* has not always been fully consistent in the AMR corpus, with annotators using *:time always*, *:mod always* and *:frequency always*. Of these, *:time always* has been the most common annotation, and *:frequency always* the least common.

Now, the AMR Checker and the AMR auto repair scripts make sure that *always* is consistently annotated as  *:time always*.

**Comment by nschneid** [comment]
Hmm, good point that "How often?" is not always a natural question for "always". OTOH, I'm not sure "When?" is natural, either.

For "Tanks are always dangerous", without context, I think the most natural question would be "Which tanks are dangerous?" (All of them.)

For "We can always hope", "She has always lived in China", etc., I wonder if `:duration` would be better??

**Comment by nschneid** [comment]
Regarding the variation in annotations for "often", "sometimes", etc.: Do you think these reflect principled distinctions, or could they all be mapped to `:frequency`?

**Comment by nschneid** [comment]
(added "seldom", "regularly", "sporadically" to the list above)

**Comment by kevincrawfordknight** [comment]
Some inconsistency in annotated data -- need some guidelines and/or AMR checker enforcement.

**Comment by nschneid** [comment]
The naacl-tutorial sentence that prompted this: "The executions are often public and almost always by hanging ." A bit weird to say `:frequency often` but `:time always`, since they have parallel roles in the sentence.
