### ISSUE TITLE
Can "but" alone trigger `:concession` (rather than `contrast-01`)?

### ISSUE THREAD

**Issue by nschneid** [amrisi/amr-guidelines#199]
Some of my students annotated a sentence along the lines of: "I recommend them [business], but prepare to pay twice as much." It seems that this can be paraphrased with "although", "however", etc., which more explicitly indicate `:concession`. Is that sufficient or is `contrast-01` the default for "but" as the sole connective? The [Dictionary entry](http://www.isi.edu/~ulf/amr/lib/amr-dict.html#:concession) does not have an analogous example.

**Comment by kevincrawfordknight** [comment]
I like :concession okay.  Annotating discourse is unfortunately still very "word-based" for AMR.  If the sentence were "I recommend them; prepare to pay twice as much", we might be inclined to put "and", even if the author's intent is almost exactly the same.

**Comment by kevincrawfordknight** [comment]
Nathan: let's document or give examples with "but"
Tim: Concession "but" is talked about in the literature
