### ISSUE TITLE
"favorite"

### ISSUE THREAD

**Issue by nschneid** [amrisi/amr-guidelines#200]
The adjective "favorite" is weird. Two questions:

1. Should it be aliased to `favor-01`? This seems to be the majority opinion of annotators, though some put `:mod favorite`.

2. What should be done with "my personal favorite", "my least favorite", "my 2nd favorite", etc.?

**Comment by kevincrawfordknight** [comment]
For "my personal favorite", I kind of like "(t / thing :arg1-of (f / favor-01 :arg0 (i / i)))".  However, it lacks the superlative-ness, so it's imperfect.  Maybe it means "the thing i like the most".  In any case, definitely drop the superfluous "personal" :)

**Comment by kevincrawfordknight** [comment]
Chinese: "most liked".

**Comment by nschneid** [comment]
"a favorite (of mine)", "one of my favorites": `include-91`

**Comment by kevincrawfordknight** [comment]
Claire: have-degree-91.
Tim: favor-01 :degree most.
Ulf: look up how we handle "2nd largest country".

**Comment by jbonn** [comment]
Question about including 'favorite' as an alias under favor-01: In "Blue is my favorite color", we would use arg1 for 'blue', but then not have a great way to handle 'color', as it is a superset that contains both arg1 and arg3 (but doesn't really fit the description of arg3 itself). There are a few different ways to in handling this, but my favorite would be adding an additional arg for the superset. Other alternatives include making a separate roleset and conflating the superset with arg2.

Blue is my favorite color.
Out of all the colors, I favor blue most.
I favor blue over other colors. 

favor-01
arg0- liker
arg1- thing prefered
arg2- instrument (the favor itself)
arg3- favored over: less favorable alternative
**arg4- superset of things out of which arg1 is favored

**Comment by jbonn** [comment]
If we had the arg4, I would think "as a color" would apply.
