### ISSUE TITLE
earliest, latest

### ISSUE THREAD

**Issue by cbonial** [amrisi/amr-guidelines#225]
It's clear to me from the updated guidelines what to do with earlier, later, using :time before or after, but it's not clear to me what to do with earliest? latest? The only consensus example is a little bit confusing because it's sort of an MWE: "next week at the earliest".  Here, the distinction between earlier/earliest is ignored, and this is also treated as :time before...  It makes sense in this example ("not expected to act before next week"), but I'm not sure how this should generalize to other usages, like "this is the earliest morphological sign of..."

**Comment by ulfulf** [comment]
Annotation of earliest/earlier/early/latest/later/late is often tricky indeed. I hope that we will soon have a frameset for "late" in the AMR Editor, and maybe for "early" as well, along with additional documentation.

Meanwhile I propose the following senses for "earliest"
 * earliest = first (in time)
   "the earliest step of epithelial invagination", "the world's earliest cities"
 * earliest = very early (superlative used as intensifier)
   "in their earliest youth", "his earliest years"
 * "at the earliest" is a somewhat idiomatic phrase, listed separately in dictionaries, meaning "not before"
   "Senate will not act until next week at the earliest." = "Senate will not act before next week."

I have already updated all 8 AMRs that contain "earliest" accordingly. Most of those AMRs needed a lot of work. But I'm certainly open to further suggestions and improvements, particularly regarding the "earliest = first (in time)" case.

"Latest" is documented in the AMR Dict and occurs in 6 consensus/guidelines AMRs. 
It is annotated as (... :mod late).
Recall that https://www.isi.edu/~ulf/amr/lib/amr-dict.html#last identifies two senses for "late"
(1) final (as in "the last week of May" or 'Johnny Ace's final words were "It's okay! Gun's not loaded… see?"')
    annotated as (... :ord (ordinal-entity :value -1))
(2) most recent/previous (as in "last week", "last October" or "latest quarter")
    annotated as (... :mod last)
"Latest" is limited to sense (2) i.e (... :mod last).

Regarding "earlier" and "later"
There are already some examples in the AMR Dict along with consensus/guidelines examples, but we need additional documentation and examples, as Tim already pointed out to me yesterday.

Tim and I propose the following annotation for cases such as "earlier in 2017" or "later on Tuesday". Example:
```
"On August 13, 1999, Steffi Graf announced her retirement later that year."
(a / announce-01
      :ARG0 (p / person :name (n / name :op1 "Steffi" :op2 "Graf"))
      :ARG1 (r / retire-01
            :ARG0 p
            :time (d / date-entity :year 1999)
            :time (a2 / after
                  :op1 d2))
      :time (d2 / date-entity :year 1999 :month 8 :day 13))
```
Sometimes the :op1 of before/after will be an implied "now", sometimes it will be totally unspecified.
The above is in line with precedents described under
    https://www.isi.edu/~ulf/amr/lib/amr-dict.html#comparative and
    https://www.isi.edu/~ulf/amr/lib/amr-dict.html#time

Upon further investigation, I think that there are some cases where the comparative forms "earlier" and "later" are used as downtoners (just as the superlative "earliest" is sometimes used as an intensified form of "early").

Examples (in contexts with absolutely no time reference point):
  * The earliest/early/earlier work of an artist.
  * The earliest/early/earlier stages of development.
  * The earliest/early/earlier chapters of a book.

Earliest = very early; earlier = somewhat early (in some contexts).

  * I'll visit Europe again in late 2018.   (less likely to include Aug./Sept. 2018)
  * I'll visit Europe again later in 2018.  (more likely to include Aug./Sept. 2018)

Later = somewhat late (in some contexts). "Latest" does not quite fall into this scheme. The latest report is the most recent report, it cannot refer to the second most recent one.

**Comment by ulfulf** [comment]
After some more thought and unease about annotating *earliest* as *first* in some cases, I think there is a viable more traditional approach for these cases after all. It often requires a combination of *have-degree-91* and *:domain* with careful attention how to fill the slots.
```
(entity {...}
    :ARG1-of (have-degree-91 :ARG2 early :ARG3 most {:ARG5 ...})
    :domain ...)
```

Examples:
```
St. Augustine was the earliest Spanish settlement in North America.
(s / settlement
  :mod (c / country :name (n / name :op1 "Spain"))
  :ARG1-of (h / have-degree-91
             :ARG2 (e / early)
             :ARG3 (m / most)
             :ARG5 (s2 / settlement
                     :location (c3 / continent :name (n3 / name :op1 "North" :op2 "America"))))
  :domain (c2 / city :name (n2 / name :op1 "St." :op2 "Augustine")))
```

```
There are some archaelogists who believe that two sites in Syria could be the world's earliest cities.
(b / believe-01
  :ARG0 (a / archaeologist
          :quant (s / some))
  :ARG1 (p / possible-01
          :ARG1 (c / city
                  :ARG1-of (h / have-degree-91
                             :ARG2 (e / early)
                             :ARG3 (m / most)
                             :ARG5 (c3 / city
                                     :location (w / world)))
                  :domain (s2 / site :quant 2
                            :location (c2 / country :name (n / name :op1 "Syria"))))))
``` 

```
The earliest to settle here was this world's largest outdoor seated bronze Buddha.
(w3 / work-of-art
  :ARG1-of (h3 / have-degree-91
             :ARG2 (e / early)
             :ARG3 (m2 / most)
             :ARG5 (s6 / statue
                     :ARG1-of (s / settle-03
                                :ARG4 (h / here))))
  :domain (w / work-of-art
            :ARG1-of (h2 / have-degree-91
                       :ARG2 (l / large)
                       :ARG3 (m / most)
                       :ARG5 (w4 / work-of-art
                               :op1 (p / person :name (n2 / name :op1 "Buddha"))
                               :location (w2 / world)
                               :location (o / outdoor)
                               :consist-of (b / bronze)
                               :ARG1-of (s2 / seat-01)))
            :mod (t / this)))
```

**Comment by nschneid** [comment]
I think the "latest" as `:mod last` policy might be confusing because "last" is also ambiguous between "final" and "most recent". Can we express it as "most recent" instead?

**Comment by ulfulf** [comment]
Yes, Nathan, "last" is ambiguous, but only the "most recent" meaning of "last" is annotated as ```:mod last```.
See https://www.isi.edu/~ulf/amr/lib/amr-dict.html#last
