### ISSUE TITLE
comparative construction + "N times"/"twice"

### ISSUE THREAD

**Issue by nschneid** [amrisi/amr-guidelines#226]
I came across some sentences like this in preposition annotation and realized this construction may be worth looking at in relation to have-degree-91 and have-quant-91.

A release search for `product-of as` returns 43 hits, mostly false positives. A few examples, some of which apparently have yet to be retrofitted:

> A study have found there are **twice as many** mixed race **people than reported in the census**.

```
(p / person
   :ARG1-of (h / have-quant-91
      :ARG2 (p2 / product-of :op1 2
         :op2 (m2 / many))
      :ARG4 (r2 / report-01
         :ARG0 (c / census))))
```

> He has killed/captured **5X as many Al-Queda terrorists** in his first 3 years **than Bush** did in all his 8 year presidency.

```
(t3 / terrorist
   :quant (p2 / product-of :op1 5 
      :op2 (n / number 
         :quant-of (t5 / terrorist 
            :ARG1-of h2 
            :ARG1-of (k2 / kill-01 [George Bush...])))))
```

> That means that today, there are 12.5 TIMES as many people in prison then just 40 years ago.

```
(m2 / mean-01
        :ARG1 (t2 / that)
        :ARG2 (p / person
              :location (p2 / prison)
              :quant (m / many
                    :degree (p3 / product-of :op1 12.5)))
        :time (t / today
              :compared-to (b / before
                    :op1 (n / now)
                    :quant (t3 / temporal-quantity :quant 40
                          :unit (y / year)
                          :mod (j / just)))))
```

[apparent structural errors: I would have done `be-located-at-91 :ARG1 (p / person) :ARG2 (p2 / prison) :time (t / today)`]

> Meaning that its economy and military are both 10 times stronger than everyone elses

```
(m / mean-01 
   :ARG2 (s / strong-02 
      :ARG1 (a / and 
         :op1 (e4 / economy 
            :poss c) 
         :op2 (m3 / military 
            :poss c)) 
      :mod (m2 / more 
         :quant (p2 / product-of :op1 10 
            :op2 (e2 / everyone 
               :mod (e3 / else))))))
```

(The last one accidentally matched the query due to another part of the sentence, so the search may need to be broadened.)

There were 13 matches for "times more", including:

> People are 2347.94 times more likely to die from smoking then from being a homosexual.

```
(l / likely-01
        :ARG1 (d / die-01
              :ARG1 (p / person)
              :ARG1-of (c / cause-01
                    :ARG0 (s / smoke-02)))
        :mod (p2 / product-of :op1 2347.94)
        :degree (m / more)
        :compared-to (d2 / die-01
              :ARG1 p
              :ARG1-of (c2 / cause-01
                    :ARG0 (h / homosexual
                          :domain p))))
```

I couldn't think of an easy way to search for comparative -er.

Is this a phenomenon worth addressing in the documentation? @cbonial, is this a candidate for the extent role of the new frames that you suggested?

**Comment by ulfulf** [comment]
Yes, Nathan, the construction certainly occurs often enough to warrant clean and consistent annotation and good documentation.

A common annotation has been ```(have-quant/degree-91 :ARG3 (more :quant (product-of :op1 factor)))```
To see examples, do a search such as *rs more :quant product-of*
But that style of annotation is not entirely satisfactory.
Sometimes annotators are able to produce correct but somewhat convoluted AMRs such as your terrorist example, but that's not always even possible.

I propose to add under the :ARG3 slot of *have-degree-91* and *have-quant-91* a new concept *times* in analogy to *more*, *less*, and *equal* as follows:
(The first examples below are classical cases with more/equal/less for comparison.)

```
The girl is 2 inches taller than the boy.
(h / have-degree-91
      :ARG1 (g / girl)
      :ARG2 (t / tall)
      :ARG3 (m / more
            :quant (d / distance-quantity :quant 2
                  :unit (i2 / inch)))
      :ARG4 (b / boy))
```

```
The girl is as tall as the boy.
(h / have-degree-91
      :ARG1 (g / girl)
      :ARG2 (t / tall)
      :ARG3 (e / equal)
      :ARG4 (b / boy))
```

```
The banana costs 25 cents less than the apple.
(h / have-quant-91
      :ARG1 (m / monetary-quantity
            :ARG2-of (c / cost-01
                  :ARG1 (b / banana)))
      :ARG3 (l / less
            :quant (m3 / monetary-quantity :quant 25
                  :unit (c3 / cent)))
      :ARG4 (m2 / monetary-quantity
            :ARG2-of (c2 / cost-01
                  :ARG1 (a / apple))))
```

```
The apple costs twice as much as the banana.
(h / have-quant-91
      :ARG1 (m / monetary-quantity
            :ARG2-of (c / cost-01
                  :ARG1 (a / apple)))
      :ARG3 (t / times :quant 2)
      :ARG4 (m2 / monetary-quantity
            :ARG2-of (c2 / cost-01
                  :ARG1 (b / banana))))
```

```
The apple costs half as much as the banana.
(h / have-quant-91
      :ARG1 (m / monetary-quantity
            :ARG2-of (c / cost-01
                  :ARG1 (a / apple)))
      :ARG3 (t / times :quant 0.5)
      :ARG4 (m2 / monetary-quantity
            :ARG2-of (c2 / cost-01
                  :ARG1 (b / banana))))
```

```
The apple costs 20% more than the banana.
(h / have-quant-91
      :ARG1 (m / monetary-quantity
            :ARG2-of (c / cost-01
                  :ARG1 (a / apple)))
      :ARG3 (t / times :quant 1.2)
      :ARG4 (m2 / monetary-quantity
            :ARG2-of (c2 / cost-01
                  :ARG1 (b / banana))))
```
