### ISSUE TITLE
string-entity

### ISSUE THREAD

**Issue by rezatakhshid** [amrisi/amr-guidelines#230]
Hi,
There are two instance of "string-entity" in the Little Prince corpus. However, nothing is explained in the manual. 
How should we annotate the expressive "What !"?
I feel like (w / what :mode expressive), my colleague disagrees!
Tnx

**Comment by ulfulf** [comment]
Just updated: https://github.com/amrisi/amr-guidelines/blob/master/amr.md
See in particular: https://amr.isi.edu/doc/amr-dict.html#string-entity

The two instances of "string-entity" in the Little Prince corpus are not the best examples of the use of "string-entity". For an exclamation of surprise ("What!"), I would agree with your
    (w / what :mode expressive)
in analogy to the "Yes!!!" example at https://www.isi.edu/~ulf/amr/lib/amr-dict.html#exclamation
However, if, based on the context, it's more of a question ("What?") then
   (a / amr-unknown) 
would be better.

**Comment by rezatakhshid** [comment]
@ulfulf Thank you very much.
