### ISSUE TITLE
Guidelines and annotation docs have different lists of reified concepts

### ISSUE THREAD

**Issue by goodmami** [amrisi/amr-guidelines#239]
The list of reified concepts at https://www.isi.edu/~ulf/amr/lib/roles.html has 7 relation-concept pairs that are not in the list at https://github.com/amrisi/amr-guidelines/blob/master/amr.md#reification:

| Relation       | Concept                |
| -------------- | ---------------------- |
| `:cost`        |  `cost-01`             |
| `:employed-by` |  `have-org-role-91`    |
| `:li`          |  `have-li-91`          |
| `:meaning`     |  `mean-01`             |
| `:ord`         |  `have-ord-91`         |
| `:role`        |  `have-org-role-91`    |
| `:superset`    |  `include-91`          |

There is also one pair in the guidelines that's not in the docs:

| Relation       | Concept                |
| -------------- | ---------------------- |
| `:value`       |  `have-value-91`       |

Should we consider the union of the two lists as the full set?

**edit**: *removed `:time` and `:topic` from the first table as they do in fact exist in both places*

**Comment by nschneid** [comment]
@ulfulf can confirm but I believe the annotation docs are more up-to-date than the guidelines.

`have-value-91` occurs in only one release AMR (in the BioAMR corpus).

**Comment by ulfulf** [comment]
Thanks for pointing this out. Some of these pairs are valid role/reification pairs, some "roles" are only shortcuts.

Valid AMR role/reification pairs:
  * :li	have-li-91  
  * :ord	have-ord-91 
  * :time	be-temporally-at-91
  * :topic	concern-02
  * :value	have-value-91   (exceedingly rare; just added to https://www.isi.edu/~ulf/amr/lib/roles.html)

Not valid AMR roles; used only as *shortcuts* in the AMR Editor:
  * :cause	cause-01
  * :cost	cost-01
  * :employed-by	have-org-role-91
  * :meaning	mean-01
  * :role	have-org-role-91
  * :subset	include-91
  * :superset	include-91

Note: The shortcuts' purpose is to make life easier for human AMR annotators. The AMR Editor automatically and instantly expands these shortcuts from pseudo-roles to their AMR reifications.
So the shortcuts will not appear in the AMR corpus.

In the table at the bottom of https://www.isi.edu/~ulf/amr/lib/roles.html these were marked as shortcuts
by being colored grey and indicating the "shortcut" nature upon mouse-over. Probably not obvious enough, so I now explicitly mark them as "shortcut only".

Updated: https://github.com/amrisi/amr-guidelines/blob/master/amr.md, https://www.isi.edu/~ulf/amr/lib/roles.html

**Comment by goodmami** [comment]
Great, thank you for clarifying and for updating the docs and guidelines. While we're on the subject, here are a few more things I noticed (after originally filing this issue):

* It appears that the arguments of `:accompanier` are backwards (should be domain=ARG1 and range=ARG0, I think). I only checked the argument order of a few roles, so there may be other occurrences.
* `:beneficiary` has two reifications in the docs (`benefit-01` and `receive-01`) but only one in the guidelines
* While many(roles)-to-one(concept) mappings seem unambiguous because they select different arguments (such as `:subset` and `:superset`), the one-to-many mappings (`:beneficiary` and `:poss`) are ambiguous. In other words, if the two concepts (`benefit-01`/`receive-01` and `have-03`/`own-01`) have different meanings, then there is information loss when collapsed to a relation and information needed for reification. Are there guidelines for dealing with these, or is it just up to the annotators intuition about which to use?

**Comment by goodmami** [comment]
4.5 years later... My question above about `:accompanier` was resolved in #269 along with `:example`. Similarly, `:poss` was addressed in #262.

I'm not sure about the `receive-01` reification of `:beneficiary`. I've been mapping it with domain=ARG2 and range=ARG0 following this frame: https://www.isi.edu/~ulf/amr/ontonotes-4.0-frames/receive-v.html.

I'll close this issue.
