### ISSUE TITLE
on the meaning of quotation marks

### ISSUE THREAD

**Issue by flipz357** [amrisi/amr-guidelines#243]
I am sorry if this has been discussed before, but I could not find something. 

Background: I notice some little inconsistencies w.r.t. quotation mark usage. For instance, in LDC17, once "Route 288, the circumferential highway...." is projected onto

```
:ARG1 (h / highway :wiki "Virginia_State_Route_288"
            :name (r / name :op1 "Route" :op2 288)
```
i.e., op2 **288**.

And in a slightly different context ("288, for those of us that actually use it..."):

```
:ARG1 (r / road :wiki "Virginia_State_Route_288" :name (x / name :op1 "288"))
```
i.e., op1 **"288"**.

Here are my questions/thoughts:

* I think it should be with quotation marks in both cases. Is this correct?
* It has been speculated that usage of quotation marks in AMR is just ["sugar/redundant"](https://github.com/cfmrp/mtool/issues/8#issuecomment-503303675) and that it is just to be more compliant with Penman language. Is this true? Maybe the guidelines could comment on this (or I missed something...)? I personally like the small, but, in my opinion, useful meaning distinction between stringified constants and constants that, e.g., represent pure numbers etc. 
* In the referenced issue it is also speculated that it should be easy to create a deterministic map from any AMR without quotes to an AMR that contains stringified nodes (a lossless reconstruction would really imply that the quotation marks are just... sugar). But I am not so sure if it is really possible.

**Comment by nschneid** [comment]
Numerals consisting digits and optionally a decimal point are recognized by the AMR Editor, which is convenient for entering quantities and values. But note that negative numbers, for example, need to be quoted. Consider the [dictionary example](https://www.isi.edu/~ulf/amr/lib/amr-dict.html):

```
(have-degree-91 :li 7 :li "-1" :ARG1 algorithm :ARG2 fast :ARG3 more)
```

So I would say in a normalized form they should all be quoted, i.e.

```
(have-degree-91 :li "7" :li "-1" :ARG1 algorithm :ARG2 fast :ARG3 more)
```

but in any case I don't know that Penman readers treat numeric constants any differently from string constants.

**Comment by flipz357** [comment]
Thanks a lot! I think quoting negative numbers also makes sense as a means of escaping the special "-" sign (e.g., in run-01, where - indicates "now comes the sense").

> but in any case I don't know that Penman readers treat numeric constants any differently from string constants.

Yes, I think it treats them the same. I just wondered, whether in AMR, the quotes carry some "meaning", in the sense that "" is like a predicate P(value) := "value" and I just don't know what P really means. But I suppose that's not really the case, or is it?

**Comment by flipz357** [comment]
Closing this since I don't know myself anymore what that issue was about
