### ISSUE TITLE
AMR Dict: :manner replaced by adjective frame

### ISSUE THREAD

**Issue by nschneid** [amrisi/amr-guidelines#244]
At https://www.isi.edu/~ulf/amr/lib/amr-dict.html#:manner and https://www.isi.edu/~ulf/amr/lib/popup/manner.html, the first example purportedly of `:manner` is actually "The boy sang very beautifully":

```lisp
(s / sing-01
      :ARG0 (b / boy)
      :ARG1-of (b2 / beautiful-02
            :degree (v / very)))
```

It is helpful to see an adjective frame example with manner semantics but it should be flagged as not using the `:manner` role.

**Comment by uhermjakob** [comment]
Thanks for catching this, Nathan.
I updated the AMR dictionary in the place you mentioned (**_:manner_**), as well as at the beginning of the **_adverb_** section.
https://www.isi.edu/~ulf/amr/lib/amr-dict.html
These inconsistencies have occasionally been introduced when the AMR corpus was updated (e.g. beautiful -> beautiful-02 after the addition of beautiful-02 to AMR concepts), but not the AMR Dictionary.
