### ISSUE TITLE
Negated Nouns

### ISSUE THREAD

**Issue by kastein** [amrisi/amr-guidelines#248]
Hello,

I'm currently working with negation in AMRs and try to figure out the correct representation for negated nouns such as "No adult spoke loudly".

Based on issue #146 and the AMR dictionary entry for quantifiers I think that the correct AMR is: 

    (a / adult :polarity -   
        :ARG0-of (s / speak-01   
            :manner (l / loud)))

But as the guidelines give the following AMRs for "No boy left" and "I have no money" I am not completely sure 

    (l / leave-01
        :ARG0 (b / boy
            :mod (n / no)))

    (h / have-03 
        :polarity -
        :ARG0 (i / i)
        :ARG1 (m / money))

Thank you very much in advance!

**Comment by nschneid** [comment]
As discussed in #146, the guidelines examples are out of date. If you could correct them in a pull request that would be appreciated!

**Comment by amrisi** [comment]
Thanks Katharina and Nathan,

I updated the _No boy left_ example in https://github.com/amrisi/amr-guidelines/blob/master/amr.md to be in sync with the AMR dict (https://www.isi.edu/~ulf/amr/lib/amr-dict.html):
```
(b / boy
     :polarity -
     :ARG0-of (l / leave-01))
```
     
The other two examples ('no adult', 'no money') are correctly annotated with _:polarity -_ at the top as in Katharina's examples above.
