### ISSUE TITLE
Disjunction of predicates under a relative clause

### ISSUE THREAD

**Issue by nschrack** [amrisi/amr-guidelines#250]
I have a question regarding disjunction of predicates under a relative clause. If there is a sentence like: 

"The man is maintaining the child who is sick or ill."

Would this be annotated as (1): 

```
(m / maintain-01
    :ARG0 (m1 / man)
    :ARG1 (o / or
         :op1 (c / child
                :ARG1-of (s / sick-05))
         :op2 (c1 / child
                :ARG1-of (i / ill-01))))
```
Or would this be annotated as (2): 
```
(m / maintain-01
    :ARG0 (m1 / man)
    :ARG1 (o / or
         :op1 (s / sick-05
                :ARG1 (c / child))
         :op2 (i / ill-01
                :ARG1 c))))
```

Or would this be annotated as (3): 
```
(m / maintain-01
    :ARG0 (m1 / man)
    :ARG1 (c / child
              :ARG1-of (s / sick-05)
              :ARG1-of (i / ill-01))))
```

The "who" would typically put the focus on the child and therefore solution 3 seems most natural. But this could then be confused with a conjunction e.g. "... the child who is sick AND ill.". Solution 2 seems to annotate that the man is maintaining the sickness not the child. Solution 1 seems to best capture the disjunction and the relative clause. Is there a better way to annotate this?

**Comment by uhermjakob** [comment]
I think the best annotation is a mix of your (2), which properly connects _or_, _sick-05_, _ill-01_ and _child_, and (3), which properly connects _maintain-01_, _man_ and _child_.

For "_The man is maintaining the child who is sick or ill._", I would recommend:
```
(m / maintain-01
      :ARG0 (m2 / man)
      :ARG1 (c / child
            :ARG1-of (s / sick-05
                  :op1-of (o / or
                        :op2 (i2 / ill-01
                              :ARG1 c)))))
```
The trick is to use the inverted role _:op1-of_, which is somewhat rare but not without precedent in the AMR corpus.

The OPs (1) means something like "The man maintains the sick child or the ill child."
The OPs (2) means something like "The man maintains the sickness or illness of the child."
The OPs (3) does indeed mean "The man maintains the child who is sick AND ill."

**Comment by nschrack** [comment]
Makes sense. Thanks for the quick response!
