### ISSUE TITLE
How AMR distinguish passive and active sentence?

### ISSUE THREAD

**Issue by 14H034160212** [amrisi/amr-guidelines#253]
Hi,

I got one question for AMR. How can I modify an AMR graph from passive to active sentence and from active to the passive sentence? Or does AMR capture the semantic representation, and it will randomly generate a passive or active sentence?

Kind regards,
Qiming

**Comment by nschneid** [comment]
AMR tries to abstract away from syntax, and so it uses semantic roles rather than syntactic relations like subject and object. Thus a passive sentence like "The window was broken by a rock" would have the same AMR as the active counterpart "A rock broke the window".

**Comment by 14H034160212** [comment]
Thanks for that. It makes more sense to me.
