### ISSUE TITLE
Can AMR distinguish the different meanings for `and` in different scenarios?

### ISSUE THREAD

**Issue by 14H034160212** [amrisi/amr-guidelines#256]
Hi,

I have one question: Will the `and` represent in AMR only mean the conjunction? Cause `and` may have multiple meanings, not only conjunction. Can AMR distinguish the different meanings for `and` in different scenarios?

The following AMR graph can represent the following sentences
AMR graph
```
(a / and
   :op1 (b / boy)
   :op2 (g / girl))
``` 
Sentences
```
the boy and the girl
both the boy and the girl
```

**Comment by nschneid** [comment]
From the perspective of how the large English release data was annotated, see https://www.isi.edu/~ulf/amr/lib/amr-dict.html

Further refinements may have been proposed in the literature.

**Comment by 14H034160212** [comment]
Thanks a lot!
