### ISSUE TITLE
Ambiguous reification of ":poss"

### ISSUE THREAD

**Issue by flipz357** [amrisi/amr-guidelines#266]
Reification of ":poss" is different from all other reification rules since it seems there are two options, using either "own-01" or "have-03". I wonder what should be preferred when reifying "poss" relation, or can it make sense to introduce an extra amr concept, such as "possession-91" to clear the ambiguity?

**Comment by flipz357** [comment]
Yup, own-01 seems more specific. Maybe it's also reflected in PropBank, where roles for have tend to be more ambiguous:

have:

Arg0-pag: owner (VN Roles: 100.1-pivot, 39.4-agent)
Arg1-ppt: possession (VN Roles: 100.1-theme, 39.4-patient) 

vs own:

Arg0-PAG: owner (VN Roles: 100-pivot)
Arg1-PPT: possession (VN Roles: 100-theme) 

Don't know if that's on purpose, though.

So it's nice to have "own" it listed before "have" in the AMR reification table, I guess.

**Comment by flipz357** [comment]
@nschneid I find that there may be also a slight contradiction in the AMR guideline regarding ":poss / own-01 / have-03".

In the guidelines it says that `In the AMR corpus, for consistency, reifications are collapsed unless needed.` I interpret "unless needed" in this case as "if it's possible to apply a dereification rule according to the guidelines, then we will do so".

So while I find that this is indeed true for other relations in the reification table, it seems different with `:poss:`.

E.g. in `bolt12_10510_9811.2` it says:

```
:op2 (e2 / enterprise
                              :ARG1-of (o / own-01
                                    :ARG0 (s / state)))
```

which, logically, if one says that reifications are collapsed per default should be:

```
:op2 (e2 / enterprise
                               :poss (s / state))
```

So even if it's technically possible, `have-03` and `own-01` do not seem to be collapsed to `:poss` in the annotated data.

**Comment by nschneid** [comment]
I think it's fine for Smatch++ to treat those as equivalent. There are cases of possession where "own" would be more or less appropriate as a lexical item in English, but I think that level of nuance in terms of reification equivalence is beyond the scope of AMR.

**Comment by flipz357** [comment]
Yup, thanks for the help!
