### ISSUE TITLE
How represent (novel) predicates not in propbank

### ISSUE THREAD

**Issue by flipz357** [amrisi/amr-guidelines#267]
I found this sense of "own" in [Cambridge dictionary](https://dictionary.cambridge.org/dictionary/english/own) which is not in PropBank:

- Last time we played them, we owned them!

- Beyoncé owned that stage tonight!

I can think of describe the first sentence as

```
defeat-01
      a0 we
      a1 they
      mod/extent total
```   

But what about the one in the second sentence? I guess it means something like the stage performance of Beyonce was super great. Given this interpretation I could build an AMR. 

So if we miss a predicate should we describe the meaning with other structure as good as possible (possibly using other dictionary definitions)? Or does AMR have a different approach to this problem?

**Comment by nschneid** [comment]
The `-00` suffix is used for missing PropBank frames. So this would be `own-00`.

**Comment by flipz357** [comment]
I see, that makes *sense* indeed!
