### ISSUE TITLE
Reference for citation

### ISSUE THREAD

**Issue by chriott** [amrisi/amr-guidelines#270]
Hi all,

I'm wondering if there is an official way to cite the AMR Little Prince Corpus version 3.0 - the download section at https://amr.isi.edu/download.html does not specify which authors were involved.

Many thanks in advance!

**Comment by flipz357** [comment]
Hi,

I think the Banarescu et al paper introduces the Little Prince corpus. I don't know if there is a paper on every version release

https://aclanthology.org/W13-2322.pdf

**Comment by chriott** [comment]
Thanks!
